version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=bycores
      - MYSQL_DATABASE=db_bycores
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  
  bycoders-backend:
    depends_on:
      - mysqldb
    build: ./bycoders-backend
    ports:
      - "6000:6000"
    expose:
      - "6000"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=ROOT
      - DB_PASSWORD=bycores
      - DB_NAME=db_bycores
      - DB_PORT=3306
    
    networks:
      - backend
      - frontend


  bycoders-frontend:
    depends_on:
      - bycoders-backend
    build:
      context: ./bycoders-frontend
      args:
        - BACKEND_URL=http://127.0.0.1:6000/api
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - frontend  
volumes: 
  db:

networks:
  backend:
  frontend: